-- Casino System Tables
DROP TABLE IF EXISTS `casino_bigwins`;
CREATE TABLE IF NOT EXISTS `casino_bigwins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(100) NOT NULL,
  `Time` BIGINT(20) NOT NULL,
  `Winner` JSON NOT NULL,
  `Prize` INT(11) NOT NULL,
  `MetaData` JSON DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `Time` (`Time`),
  KEY `Type` (`Type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `casino_statistics`;
CREATE TABLE IF NOT EXISTS `casino_statistics` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `SID` INT(11) NOT NULL,
  `stats` JSON DEFAULT NULL,
  `TotalAmountWon` BIGINT(20) NOT NULL DEFAULT 0,
  `TotalAmountLost` BIGINT(20) NOT NULL DEFAULT 0,
  `AmountWon` JSON DEFAULT NULL,
  `AmountLost` JSON DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SID` (`SID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `casino_config`;
CREATE TABLE IF NOT EXISTS `casino_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `data` JSON NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 