-- Miscellaneous System Tables
DROP TABLE IF EXISTS `sequence`;
CREATE TABLE IF NOT EXISTS `sequence` (
  `key` VARCHAR(255) NOT NULL,
  `current` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `roles`;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `Abv` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Queue` JSON NOT NULL,
  `Permission` JSON NOT NULL,
  `default` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = latin1; 

DROP TABLE IF EXISTS `defaults`;
CREATE TABLE IF NOT EXISTS `defaults` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `collection` VARCHAR(255) NOT NULL UNIQUE,
  `date` BIGINT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255),
  `forum` VARCHAR(255),
  `account` VARCHAR(255),
  `identifier` VARCHAR(255) UNIQUE,
  `verified` TINYINT DEFAULT 0,
  `joined` BIGINT,
  `groups` JSON,
  `avatar` VARCHAR(255),
  `priority` INT DEFAULT 0,
  `tokens` JSON,
  `default` TINYINT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `bans`;
CREATE TABLE IF NOT EXISTS `bans` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `account` INT,
  `identifier` VARCHAR(255),
  `expires` BIGINT,
  `reason` TEXT,
  `issuer` VARCHAR(255),
  `active` TINYINT(1) DEFAULT 1,
  `started` BIGINT,
  `tokens` JSON,
  `unbanned` JSON,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_account` (`account`),
  INDEX `idx_identifier` (`identifier`),
  INDEX `idx_active` (`active`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `logs`;
CREATE TABLE IF NOT EXISTS `logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` BIGINT NOT NULL,
  `level` VARCHAR(50) NOT NULL,
  `component` VARCHAR(100) NOT NULL,
  `log` TEXT NOT NULL,
  `data` JSON NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `changelogs`;
CREATE TABLE IF NOT EXISTS `changelogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` BIGINT(20) NOT NULL,
  `title` VARCHAR(255) DEFAULT NULL,
  `content` TEXT DEFAULT NULL,
  `version` VARCHAR(50) DEFAULT NULL,
  `author` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `locations`;
CREATE TABLE IF NOT EXISTS `locations` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `Type` VARCHAR(50) NOT NULL DEFAULT 'spawn',
  `Name` VARCHAR(100) NOT NULL,
  `Heading` FLOAT NOT NULL DEFAULT 0,
  `Coords` JSON NOT NULL,
  `default` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `storage_units`;
CREATE TABLE IF NOT EXISTS `storage_units` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `owner` JSON DEFAULT NULL,
  `level` INT(11) NOT NULL DEFAULT 1,
  `location` JSON NOT NULL,
  `managedBy` VARCHAR(100) NOT NULL,
  `lastAccessed` BIGINT(20) DEFAULT NULL,
  `passcode` VARCHAR(8) NOT NULL DEFAULT '0000',
  `soldBy` JSON DEFAULT NULL,
  `soldAt` BIGINT(20) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `managedBy` (`managedBy`),
  KEY `level` (`level`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `placed_props`;
CREATE TABLE IF NOT EXISTS `placed_props` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `model` varchar(255) NOT NULL DEFAULT '',
  `coords` varchar(255) NOT NULL,
  `heading` double NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `creator` bigint(20) NOT NULL,
  `is_frozen` tinyint(1) NOT NULL DEFAULT 0,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `type` int(11) NOT NULL DEFAULT 0,
  `name_override` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `weed`;
CREATE TABLE IF NOT EXISTS `weed` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_male` TINYINT(1) NOT NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `z` DOUBLE NOT NULL,
  `growth` FLOAT NOT NULL DEFAULT 0,
  `output` FLOAT NOT NULL DEFAULT 1,
  `material` INT(11) NOT NULL,
  `planted` INT(11) NOT NULL,
  `water` FLOAT NOT NULL DEFAULT 100,
  `fertilizer_type` VARCHAR(32) DEFAULT NULL,
  `fertilizer_value` FLOAT DEFAULT NULL,
  `fertilizer_time` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `billboards`;
CREATE TABLE IF NOT EXISTS `billboards` (
  `billboardId` VARCHAR(64) NOT NULL,
  `billboardUrl` VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY (`billboardId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `scenes`;
CREATE TABLE IF NOT EXISTS `scenes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `route` INT NOT NULL DEFAULT 1,
  `text` TEXT NOT NULL,
  `font` INT NOT NULL DEFAULT 1,
  `size` FLOAT NOT NULL DEFAULT 0.35,
  `outline` TINYINT(1) NOT NULL DEFAULT 0,
  `text_color_r` INT NOT NULL DEFAULT 255,
  `text_color_g` INT NOT NULL DEFAULT 255,
  `text_color_b` INT NOT NULL DEFAULT 255,
  `background_type` INT NOT NULL DEFAULT 0,
  `background_opacity` INT NOT NULL DEFAULT 255,
  `background_color_r` INT NOT NULL DEFAULT 255,
  `background_color_g` INT NOT NULL DEFAULT 255,
  `background_color_b` INT NOT NULL DEFAULT 255,
  `background_h` FLOAT NOT NULL DEFAULT 0.02,
  `background_w` FLOAT NOT NULL DEFAULT 0.0,
  `background_x` FLOAT NOT NULL DEFAULT 0.0,
  `background_y` FLOAT NOT NULL DEFAULT 0.0,
  `background_rotation` FLOAT NOT NULL DEFAULT 0.0,
  `length` INT NOT NULL DEFAULT 6,
  `distance` FLOAT NOT NULL DEFAULT 7.5,
  `expires` BIGINT NULL DEFAULT NULL,
  `staff` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `meth_tables`;
CREATE TABLE IF NOT EXISTS `meth_tables` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tier` int(11) NOT NULL DEFAULT 1,
  `created` bigint(20) NOT NULL,
  `cooldown` bigint(20) DEFAULT NULL,
  `recipe` varchar(512) NOT NULL,
  `active_cook` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `placed_meth_tables`;
CREATE TABLE IF NOT EXISTS `placed_meth_tables` (
  `table_id` int(11) NOT NULL,
  `owner` bigint(20) DEFAULT NULL,
  `placed` bigint(20) NOT NULL DEFAULT 0,
  `expires` bigint(20) NOT NULL DEFAULT 0,
  `coords` varchar(255) NOT NULL,
  `heading` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`table_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `business_tvs`;
CREATE TABLE IF NOT EXISTS `business_tvs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tv` VARCHAR(100) NOT NULL,
  `link` TEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tv` (`tv`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 