-- Tracks System Tables
DROP TABLE IF EXISTS `tracks`;
CREATE TABLE IF NOT EXISTS `tracks` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `SID` VARCHAR(50) NOT NULL,
  `tracks` JSON DEFAULT '[]',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sid` (`SID`)
);

DROP TABLE IF EXISTS `tracks_pd`;
CREATE TABLE IF NOT EXISTS `tracks_pd` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `SID` VARCHAR(50) NOT NULL,
  `tracks` JSON DEFAULT '[]',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sid` (`SID`)
); 